version: '3'

services:
  activity_generator_service:
    build: activity_generator_service/.
    ports:
      - 8081:8000
    restart: always

networks: 
  default: 
    external: 
      name: awesome_service_network