version: '3'

services:
  detailed_info_scraper_service:
    build: detailed_info_scraper_service/.
    restart: always
    environment:
      - PYTHONUNBUFFERED=1

networks: 
  default: 
    external: 
      name: awesome_service_network