version: '3'

services:
  postgres:
    image: postgres:13
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - example-service-postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "example"]
      interval: 5s
      retries: 5
    restart: always

  api:
    build: service_api/.
    ports:
      - 18080:8080

volumes:
  example-service-postgres-db-volume:

networks: 
  default: 
    external: 
      name: awesome_service_network